var grid = require('../')(4)
var data = grid()
data = data.concat(grid(data[5]))
data = data.concat(grid(data[6]))
data = data.concat(grid(data[26]))
data = data.concat(grid(data[3]))
data = data.concat(grid(data[13]))
data = data.concat(grid(data[40]))
data = data.concat(grid(data[50]))
data = data.concat(grid(data[80]))
data = data.concat(grid(data[90]))
console.log(JSON.stringify(data,null,2))
